# Install NVIDIA GPU image
FROM nvidia/cuda:9.2-cudnn7-devel

# Install dependencies
RUN apt-get update && apt-get install -y --no-install-recommends python3-dev python3-pip python3-nose python3-setuptools libblas-dev liblapack-dev cmake ffmpeg gfortran git && rm -rf /var/lib/apt/lists/*



# Set up .theanorc for CUDA
#RUN echo "[global]\ndevice=cuda\nfloatX=float32\noptimizer_including=cudnn\n[lib]\ncnmem=0.1\n[nvcc]\nfastmath=True" > /root/.theanorc

# Install Lasagne
RUN pip3 install https://github.com/Lasagne/Lasagne/archive/master.zip

# Install required Python packages
RUN pip3 install librosa future

# Import all scripts
COPY . ./

# Fetch model
ADD https://tuc.cloud/index.php/s/m9smX4FkqmJaxLW/download ./model/BirdNET_Soundscape_Model.pkl

# Add entry point to run the script
ENTRYPOINT [ "python3", "./analyze.py" ]